## Event emitted when money is gained or spent.
## Used for tracking economy flow and enabling economy-based conditions.
class_name EconomyEvent
extends GameEvent

## Types of economy transactions
enum TransactionType {
	RUNE_ACTIVATION,   ## Money generated by a rune effect
	SHOP_PURCHASE,     ## Bought something from the shop
	SHOP_SELL,         ## Sold something to the shop
	ROUND_BONUS,       ## Bonus for winning a round
	INTEREST,          ## Interest on saved money
	COST,              ## Generic cost (upgrade, reroll, etc.)
}

## The type of transaction
var transaction_type: TransactionType

## Amount of money (positive = gain, negative = loss)
var amount: int = 0

## Money before this transaction
var balance_before: int = 0

## Money after this transaction
var balance_after: int = 0

## The source of this transaction (rune ID, shop item, etc.)
var source: StringName = &""

## Optional description for UI display
var description: String = ""


func _init() -> void:
	super._init()


func get_event_type() -> StringName:
	return &"EconomyEvent"


## Factory for rune-generated money
static func create_rune_income(rune_id: StringName, amount: int, balance_before: int) -> EconomyEvent:
	var event = EconomyEvent.new()
	event.transaction_type = TransactionType.RUNE_ACTIVATION
	event.source = rune_id
	event.amount = amount
	event.balance_before = balance_before
	event.balance_after = balance_before + amount
	event.description = "Rune activation: %s" % rune_id
	return event


## Factory for shop purchase
static func create_purchase(item_id: StringName, cost: int, balance_before: int) -> EconomyEvent:
	var event = EconomyEvent.new()
	event.transaction_type = TransactionType.SHOP_PURCHASE
	event.source = item_id
	event.amount = -cost
	event.balance_before = balance_before
	event.balance_after = balance_before - cost
	event.description = "Purchased: %s" % item_id
	return event


## Factory for round bonus
static func create_round_bonus(round_number: int, bonus: int, balance_before: int) -> EconomyEvent:
	var event = EconomyEvent.new()
	event.transaction_type = TransactionType.ROUND_BONUS
	event.source = &"round_%d" % round_number
	event.amount = bonus
	event.balance_before = balance_before
	event.balance_after = balance_before + bonus
	event.description = "Round %d victory bonus" % round_number
	return event


func to_dict() -> Dictionary:
	var base = super.to_dict()
	base.merge({
		"transaction_type": TransactionType.keys()[transaction_type],
		"amount": amount,
		"balance_before": balance_before,
		"balance_after": balance_after,
		"source": source,
		"description": description,
	})
	return base


func get_summary() -> String:
	var sign = "+" if amount >= 0 else ""
	return "[Economy] %s%d$ (%s) | Balance: %d → %d" % [
		sign, amount, TransactionType.keys()[transaction_type], balance_before, balance_after
	]
